# =============================================================================
# Logging Configuration - Production
# Comprehensive logging for production training
# =============================================================================

# Standard console logging
console_log_interval: 2000  # Less frequent for production
log_level: "INFO"

# Full TensorBoard logging
tensorboard:
  enabled: true
  log_dir: "./logs/production"
  log_scalars: true
  log_histograms: true  # Enable for analysis
  log_images: false

# W&B enabled for production tracking
wandb:
  enabled: true  # Enable for production
  project: "tvc-ai-production"
  entity: null  # Set your W&B username
  tags: ["production", "sac", "rocket", "tvc", "v1"]
  notes: "Production SAC training for rocket TVC control with full domain randomization"

# Production model saving
model_save_interval: 100000  # Less frequent saves
save_replay_buffer: true  # Save buffer for analysis

# Comprehensive video recording
video_recording:
  enabled: true
  record_freq: 200000  # Less frequent but comprehensive
  video_length: 500  # Longer videos for analysis
