# =============================================================================
# Training Configuration - Improved
# Simple configuration matching train.py expectations
# =============================================================================

# Training parameters
total_steps: 650000
eval_freq: 5000
eval_episodes: 20
final_eval_episodes: 50
checkpoint_freq: 50000

# Early stopping
early_stopping:
  enabled: true
  patience: 10
  min_improvement: 0.01
