# =============================================================================
# Training Configuration - Production
# Extended training for final model development
# =============================================================================

# Extended training for maximum performance
total_steps: 5000000  # Very long training
eval_freq: 50000  # Less frequent but more thorough evaluation
eval_episodes: 50  # More episodes per evaluation
final_eval_episodes: 100  # Comprehensive final evaluation

# Less frequent checkpointing to save space
checkpoint_freq: 100000  # Less frequent checkpoints
save_best_model: true
save_last_model: true

# Conservative early stopping
early_stopping:
  enabled: true
  patience: 15  # More patience for long training
  min_improvement: 0.005  # Smaller improvement threshold
  metric: "eval_reward_mean"

# Parallel environments for faster training
env_parallel: false  # Can be enabled if supported
num_envs: 1  # Can be increased for parallel training

# Full curriculum learning for progressive difficulty
curriculum:
  enabled: true
  stages:
    - name: "basic_stabilization"
      duration: 1000000
      max_initial_tilt: 1.0
      max_gimbal_angle: 15.0
    - name: "intermediate_control"
      duration: 1500000
      max_initial_tilt: 3.0
      max_gimbal_angle: 20.0
    - name: "advanced_control"
      duration: 1500000
      max_initial_tilt: 7.0
      max_gimbal_angle: 25.0
    - name: "expert_control"
      duration: 1000000
      max_initial_tilt: 12.0
      max_gimbal_angle: 25.0
