# =============================================================================
# Training Configuration - Standard
# Default training settings for most use cases
# =============================================================================

# Training duration and checkpointing
total_steps: 2000000  # Total training steps
eval_freq: 25000  # Evaluation frequency
eval_episodes: 20  # Episodes per evaluation
final_eval_episodes: 50  # Final evaluation episodes

# Model saving and checkpointing
checkpoint_freq: 50000  # Model checkpoint frequency
save_best_model: true  # Save best model based on evaluation
save_last_model: true  # Save last model

# Early stopping
early_stopping:
  enabled: true
  patience: 10  # Evaluations without improvement
  min_improvement: 0.01  # Minimum improvement threshold
  metric: "eval_reward_mean"  # Metric to monitor

# Training environment settings
env_parallel: false  # Use parallel environments
num_envs: 1  # Number of parallel environments

# Curriculum learning
curriculum:
  enabled: false
  stages:
    - name: "basic_stabilization"
      duration: 500000
      max_initial_tilt: 1.0
      max_gimbal_angle: 15.0
    - name: "advanced_control"
      duration: 1000000
      max_initial_tilt: 5.0
      max_gimbal_angle: 25.0
    - name: "full_challenge"
      duration: 500000
      max_initial_tilt: 10.0
      max_gimbal_angle: 25.0
