# =============================================================================
# Environment Configuration - Minimal
# Simplified environment for quick testing and debugging
# =============================================================================

# Environment type and basic settings
env_id: "RocketTVC-v1"
max_episode_steps: 500
render_mode: "human"  # Enable visualization for debugging
physics_timestep: 0.01  # Faster timestep for quicker simulation
control_frequency: 25  # Hz, reduced for faster processing

# Simplified rocket properties
rocket:
  mass: 1.5
  radius: 0.05
  length: 0.8
  inertia_ratio: 10.0
  thrust_mean: 40.0  # Reduced thrust for easier control
  thrust_std: 2.0
  burn_time: 3.0
  max_gimbal_angle: 15.0  # Reduced for simpler control
  gimbal_response_time: 0.05
  max_gimbal_rate: 50.0  # Reduced for stability
  initial_altitude: 1.0
  target_altitude: 3.0  # Lower target for easier success
  max_initial_tilt: 1.0  # Minimal initial disturbance
  max_initial_angular_vel: 0.2

# No domain randomization for consistent testing
domain_randomization:
  enabled: false
  mass_variation: 0.0
  cg_offset_max: 0.0
  inertia_variation: 0.0
  thrust_variation: 0.0
  burn_time_variation: 0.0
  gravity_variation: 0.0
  air_density_variation: 0.0
  wind_force_max: 0.0
  gimbal_delay_max: 0.0
  gimbal_noise_std: 0.0

# No sensor noise for clean testing
sensor_noise:
  enabled: false
  gyro_noise_std: 0.0
  gyro_bias_max: 0.0
  gyro_drift_rate: 0.0
  quaternion_noise_std: 0.0
  attitude_delay_max: 0.0
  sensor_dropout_prob: 0.0
  sensor_saturation_threshold: 1.0

# Simplified reward function
reward:
  attitude_penalty_gain: 10.0
  angular_velocity_penalty_gain: 0.1
  altitude_bonus_gain: 0.5
  control_effort_penalty_gain: 0.01
  saturation_threshold: 0.8
  saturation_penalty: 1.0
  efficiency_bonus: 0.2
  stability_angle_threshold: 5.0  # More lenient
  stability_angular_vel_threshold: 1.0  # More lenient
  stability_bonus: 1.0
  tilt_improvement_bonus: 0.5
  tilt_degradation_penalty: 1.0
  nominal_altitude_bonus: 0.1
  failure_penalty: -50.0  # Less harsh
  crash_penalty: -100.0
  sparse_rewards: false
  reward_scaling: 1.0

# Lenient termination conditions
termination:
  max_tilt_angle: 60.0  # More lenient
  max_angular_velocity: 15.0  # More lenient
  min_altitude: 0.1
  max_altitude: 10.0
  max_episode_time: 15.0  # Shorter episodes
  success_angle_threshold: 10.0  # More lenient
  success_stability_time: 1.0  # Shorter stability requirement
