# =============================================================================
# Environment Configuration - Default
# Standard rocket TVC environment configuration
# =============================================================================

# Environment type and basic settings
env_id: "RocketTVC-v1"
max_episode_steps: 1500
render_mode: null  # null, "human", "rgb_array"
physics_timestep: 0.004167  # 1/240 seconds
control_frequency: 50  # Hz, agent control frequency

# Rocket physical properties
rocket:
  # Basic physical parameters
  mass: 1.5  # kg, dry mass
  radius: 0.05  # m, rocket radius
  length: 0.8  # m, rocket length
  inertia_ratio: 10.0  # I_xx / I_zz ratio
  
  # Motor specifications
  thrust_mean: 50.0  # N, average thrust
  thrust_std: 5.0  # N, thrust variation
  burn_time: 3.0  # s, motor burn time
  
  # TVC system parameters
  max_gimbal_angle: 25.0  # degrees, maximum gimbal deflection
  gimbal_response_time: 0.05  # s, servo response time
  max_gimbal_rate: 100.0  # degrees/s, maximum gimbal rate
  
  # Initial conditions
  initial_altitude: 1.0  # m, starting altitude
  target_altitude: 5.0  # m, target altitude
  max_initial_tilt: 2.0  # degrees, maximum random initial tilt
  max_initial_angular_vel: 0.5  # rad/s, maximum random initial angular velocity

# Domain randomization for robust training
domain_randomization:
  enabled: true
  
  # Mass and inertia randomization
  mass_variation: 0.2  # ±20% mass variation
  cg_offset_max: 0.05  # m, maximum center of gravity offset
  inertia_variation: 0.15  # ±15% inertia variation
  
  # Thrust and motor randomization
  thrust_variation: 0.3  # ±30% thrust variation
  burn_time_variation: 0.1  # ±10% burn time variation
  
  # Environmental conditions
  gravity_variation: 0.02  # ±2% gravity variation
  air_density_variation: 0.1  # ±10% air density variation
  wind_force_max: 2.0  # N, maximum wind force
  
  # Hardware variations
  gimbal_delay_max: 0.02  # s, maximum additional gimbal delay
  gimbal_noise_std: 0.01  # standard deviation of gimbal position noise

# Sensor noise modeling
sensor_noise:
  enabled: true
  
  # Gyroscope noise
  gyro_noise_std: 0.1  # rad/s, gyroscope noise
  gyro_bias_max: 0.05  # rad/s, maximum gyro bias
  gyro_drift_rate: 0.001  # rad/s/s, gyro drift rate
  
  # Attitude estimation noise
  quaternion_noise_std: 0.01  # quaternion noise
  attitude_delay_max: 0.01  # s, maximum attitude estimation delay
  
  # Additional sensor effects
  sensor_dropout_prob: 0.01  # probability of sensor dropout
  sensor_saturation_threshold: 0.95  # saturation threshold

# Reward function configuration
reward:
  # Primary objectives
  attitude_penalty_gain: 15.0  # penalty for attitude deviation
  angular_velocity_penalty_gain: 0.2  # penalty for high angular velocity
  altitude_bonus_gain: 1.0  # bonus for maintaining target altitude
  
  # Control efficiency
  control_effort_penalty_gain: 0.02  # penalty for large control inputs
  saturation_threshold: 0.8  # control saturation threshold
  saturation_penalty: 2.0  # penalty for control saturation
  efficiency_bonus: 0.5  # bonus for fuel efficiency
  
  # Stability rewards
  stability_angle_threshold: 3.0  # degrees, stable attitude threshold
  stability_angular_vel_threshold: 0.5  # rad/s, stable rate threshold
  stability_bonus: 2.0  # bonus for maintaining stability
  
  # Performance bonuses
  tilt_improvement_bonus: 1.0  # bonus for reducing tilt
  tilt_degradation_penalty: 2.0  # penalty for increasing tilt
  nominal_altitude_bonus: 0.2  # bonus for staying in safe altitude
  
  # Safety constraints
  failure_penalty: -100.0  # penalty for mission failure
  crash_penalty: -200.0  # penalty for rocket crash
  
  # Sparse vs dense rewards
  sparse_rewards: false  # use dense shaping vs sparse terminal rewards
  reward_scaling: 1.0  # global reward scaling factor

# Termination conditions
termination:
  # Attitude limits
  max_tilt_angle: 45.0  # degrees, maximum allowed tilt
  max_angular_velocity: 10.0  # rad/s, maximum angular velocity
  
  # Altitude limits
  min_altitude: 0.2  # m, minimum safe altitude
  max_altitude: 20.0  # m, maximum allowed altitude
  
  # Time limits
  max_episode_time: 30.0  # s, maximum episode duration
  
  # Success criteria
  success_angle_threshold: 5.0  # degrees, angle for success
  success_stability_time: 2.0  # s, time to maintain stability for success
