# =============================================================================
# Environment Configuration - Evaluation
# Configuration for model evaluation and testing
# =============================================================================

# Environment type and basic settings
env_id: "RocketTVC-v1"
max_episode_steps: 1500
render_mode: null  # Can be overridden for visualization
physics_timestep: 0.004167  # Standard timestep
control_frequency: 50  # Standard frequency

# Standard rocket properties for consistent evaluation
rocket:
  mass: 1.5
  radius: 0.05
  length: 0.8
  inertia_ratio: 10.0
  thrust_mean: 50.0
  thrust_std: 5.0
  burn_time: 3.0
  max_gimbal_angle: 25.0
  gimbal_response_time: 0.05
  max_gimbal_rate: 100.0
  initial_altitude: 1.0
  target_altitude: 5.0
  max_initial_tilt: 2.0
  max_initial_angular_vel: 0.5

# Evaluation-specific domain randomization
domain_randomization:
  enabled: true  # Enable for robustness evaluation
  mass_variation: 0.15  # Moderate variation for evaluation
  cg_offset_max: 0.03
  inertia_variation: 0.1
  thrust_variation: 0.2
  burn_time_variation: 0.05
  gravity_variation: 0.01
  air_density_variation: 0.05
  wind_force_max: 1.5
  gimbal_delay_max: 0.01
  gimbal_noise_std: 0.005

# Moderate sensor noise for realistic evaluation
sensor_noise:
  enabled: true
  gyro_noise_std: 0.08
  gyro_bias_max: 0.03
  gyro_drift_rate: 0.0005
  quaternion_noise_std: 0.008
  attitude_delay_max: 0.005
  sensor_dropout_prob: 0.005
  sensor_saturation_threshold: 0.95

# Standard reward function for evaluation
reward:
  attitude_penalty_gain: 15.0
  angular_velocity_penalty_gain: 0.2
  altitude_bonus_gain: 1.0
  control_effort_penalty_gain: 0.02
  saturation_threshold: 0.8
  saturation_penalty: 2.0
  efficiency_bonus: 0.5
  stability_angle_threshold: 3.0
  stability_angular_vel_threshold: 0.5
  stability_bonus: 2.0
  tilt_improvement_bonus: 1.0
  tilt_degradation_penalty: 2.0
  nominal_altitude_bonus: 0.2
  failure_penalty: -100.0
  crash_penalty: -200.0
  sparse_rewards: false
  reward_scaling: 1.0

# Standard termination conditions
termination:
  max_tilt_angle: 45.0
  max_angular_velocity: 10.0
  min_altitude: 0.2
  max_altitude: 20.0
  max_episode_time: 30.0
  success_angle_threshold: 5.0
  success_stability_time: 2.0
