# =============================================================================
# Environment Configuration - Production
# High-fidelity environment for final model training
# =============================================================================

# Environment type and basic settings
env_id: "RocketTVC-v1"
max_episode_steps: 2000
render_mode: null
physics_timestep: 0.002083  # 1/480 seconds for higher precision
control_frequency: 100  # Higher frequency control

# Detailed rocket model
rocket:
  mass: 1.5
  radius: 0.05
  length: 0.8
  inertia_ratio: 12.0  # More realistic inertia ratio
  thrust_mean: 55.0  # Higher thrust for more challenge
  thrust_std: 8.0  # Higher variation
  burn_time: 3.5
  max_gimbal_angle: 25.0
  gimbal_response_time: 0.03  # Faster servos
  max_gimbal_rate: 150.0  # Higher rate capability
  initial_altitude: 1.0
  target_altitude: 8.0  # Higher target altitude
  max_initial_tilt: 5.0  # More challenging initial conditions
  max_initial_angular_vel: 1.0

# Maximum domain randomization for robustness
domain_randomization:
  enabled: true
  mass_variation: 0.25  # ±25% mass variation
  cg_offset_max: 0.06  # 6cm CG offset
  inertia_variation: 0.2  # ±20% inertia variation
  thrust_variation: 0.35  # ±35% thrust variation
  burn_time_variation: 0.15  # ±15% burn time variation
  gravity_variation: 0.03  # ±3% gravity variation
  air_density_variation: 0.15  # ±15% air density variation
  wind_force_max: 3.0  # Stronger wind disturbances
  gimbal_delay_max: 0.025  # Additional gimbal delays
  gimbal_noise_std: 0.015  # More gimbal noise

# Realistic sensor noise
sensor_noise:
  enabled: true
  gyro_noise_std: 0.15  # Higher gyro noise
  gyro_bias_max: 0.08  # Higher bias
  gyro_drift_rate: 0.002  # More drift
  quaternion_noise_std: 0.015  # More attitude noise
  attitude_delay_max: 0.015  # More delay
  sensor_dropout_prob: 0.02  # 2% dropout probability
  sensor_saturation_threshold: 0.9  # Earlier saturation

# Optimized reward function for production
reward:
  attitude_penalty_gain: 20.0  # Higher penalty for precision
  angular_velocity_penalty_gain: 0.3
  altitude_bonus_gain: 1.5
  control_effort_penalty_gain: 0.03
  saturation_threshold: 0.75  # Stricter saturation limit
  saturation_penalty: 3.0  # Higher penalty
  efficiency_bonus: 0.8
  stability_angle_threshold: 2.0  # Stricter stability requirement
  stability_angular_vel_threshold: 0.3  # Stricter rate requirement
  stability_bonus: 3.0  # Higher bonus for stability
  tilt_improvement_bonus: 1.5
  tilt_degradation_penalty: 2.5
  nominal_altitude_bonus: 0.3
  failure_penalty: -150.0  # Higher failure penalty
  crash_penalty: -300.0  # Much higher crash penalty
  sparse_rewards: false
  reward_scaling: 1.0

# Strict termination conditions
termination:
  max_tilt_angle: 35.0  # Stricter tilt limit
  max_angular_velocity: 8.0  # Stricter rate limit
  min_altitude: 0.3
  max_altitude: 25.0
  max_episode_time: 40.0  # Longer episodes for complexity
  success_angle_threshold: 3.0  # Stricter success criteria
  success_stability_time: 3.0  # Longer stability requirement
