# =============================================================================
# TVC-AI Minimal Training Configuration
# Optimized for fast learning and development
# =============================================================================

defaults:
  - _self_

# =============================================================================
# GLOBAL SETTINGS
# =============================================================================
globals:
  project_name: "TVC-AI-Minimal"
  experiment_name: "rocket_tvc_minimal_fast"
  output_dir: "./outputs/minimal/${now:%Y-%m-%d}/${now:%H-%M-%S}"
  seed: 42
  debug: false
  device: "auto"

# =============================================================================
# WEIGHTS & BIASES CONFIGURATION (DISABLED FOR SPEED)
# =============================================================================
wandb:
  enabled: false
  project: "tvc-ai-minimal"
  run_name: "${globals.experiment_name}"
  tags: ["sac", "rocket", "minimal", "fast"]
  mode: "disabled"

# =============================================================================
# TRAINING CONFIGURATION (OPTIMIZED FOR SPEED)
# =============================================================================
training:
  total_steps: 150000      # Fast training
  eval_freq: 3000          # Frequent evaluation
  eval_episodes: 8         # Quick evaluation
  final_eval_episodes: 20
  checkpoint_freq: 15000

  # Aggressive early stopping for speed
  early_stopping:
    enabled: true
    patience: 4
    min_improvement: 0.05

# =============================================================================
# AGENT CONFIGURATION (OPTIMIZED FOR FAST LEARNING)
# =============================================================================
agent:
  # Smaller network for speed
  hidden_dims: [256, 256]
  layer_norm: true
  activation: "relu"

  # Optimized learning rates for fast convergence
  lr_actor: 0.001
  lr_critic: 0.001
  lr_alpha: 0.001

  # SAC hyperparameters optimized for speed
  gamma: 0.95              # Lower for faster learning
  tau: 0.01               # Faster target updates
  alpha: 0.1
  automatic_entropy_tuning: true

  # Training parameters optimized for speed
  batch_size: 256
  buffer_size: 50000      # Small buffer for speed
  learning_starts: 1000   # Start training early
  train_freq: 1
  gradient_steps: 1

# =============================================================================
# ENVIRONMENT CONFIGURATION (SIMPLIFIED FOR FAST LEARNING)
# =============================================================================
env:
  max_episode_steps: 800
  render_mode: null
  
  # Start simple, no randomization
  domain_randomization: false
  sensor_noise: false

# =============================================================================
# ROCKET PHYSICS (SIMPLIFIED)
# =============================================================================
# Simplified rocket parameters for faster learning
mass: 2.0
length: 1.0
radius: 0.05
thrust_max: 35.0
thrust_std: 0.5
max_gimbal_angle: 18.0
max_initial_tilt: 1.5    # Very small initial tilt
wind_force_max: 0.3      # Minimal wind

# Simplified reward function
attitude_penalty_gain: 8.0
angular_velocity_penalty_gain: 0.1
control_effort_penalty_gain: 0.01
stability_bonus: 1.5

# =============================================================================
# LOGGING CONFIGURATION (MINIMAL)
# =============================================================================
logging:
  log_level: "INFO"
  console_log_interval: 5
  metrics_window: 50
  
  # TensorBoard only
  tensorboard:
    enabled: true
    log_histograms: false
    log_scalars: true
    log_images: false

# =============================================================================
# HYDRA CONFIGURATION
# =============================================================================
hydra:
  run:
    dir: ${globals.output_dir}
  job:
    name: tvc_ai_minimal_training
