# =============================================================================
# TVC-AI Training Configuration
# Main training entry point configuration
# =============================================================================

defaults:
  - env: default
  - agent: sac_default
  - training: standard
  - logging: standard
  - _self_

# =============================================================================
# GLOBAL SETTINGS
# =============================================================================
globals:
  project_name: "TVC-AI"
  experiment_name: "rocket_tvc_sac_v2"
  output_dir: "./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}"
  seed: 42
  debug: false
  device: "auto"  # auto, cpu, cuda
  num_workers: 4  # For parallel environment sampling

# =============================================================================
# WEIGHTS & BIASES CONFIGURATION
# =============================================================================
wandb:
  enabled: false
  project: "tvc-ai"
  entity: null
  tags: ["sac", "rocket", "tvc"]
  notes: "Rocket TVC control with SAC"
  mode: "online"  # online, offline, disabled

# =============================================================================
# HYDRA CONFIGURATION
# =============================================================================
hydra:
  run:
    dir: ${globals.output_dir}
  job:
    name: tvc_ai_training
  
# Override any parameters from command line or other configs
# Example usage: python scripts/train.py env.rocket.mass=2.0 training.total_steps=1000000
