# =============================================================================
# SAC Agent Configuration - Production
# High-performance configuration for final model training
# =============================================================================

# Advanced network architecture
architecture:
  hidden_dims: [512, 512, 512, 256]  # Deeper network
  activation: "swish"  # Better activation function
  layer_norm: true  # Layer normalization for stability
  dropout: 0.1  # Dropout for regularization
  
  actor:
    final_activation: "tanh"
    log_std_bounds: [-20, 2]
    mean_range: 1.0
  
  critic:
    num_critics: 2
    use_spectral_norm: true  # Spectral normalization for stability

# Optimized learning rates and advanced optimization
optimization:
  lr_actor: 8e-5  # Lower learning rate for stability
  lr_critic: 2e-4  # Lower learning rate for stability
  lr_alpha: 2e-4
  optimizer: "adamw"  # AdamW for better regularization
  weight_decay: 1e-4  # Higher weight decay
  grad_clip_norm: 5.0  # Stricter gradient clipping
  
  # Learning rate scheduling for long training
  lr_schedule:
    enabled: true
    type: "cosine"
    warmup_steps: 50000
    decay_steps: 1500000

# SAC parameters optimized for performance
sac:
  gamma: 0.998  # Higher discount for long-term planning
  tau: 0.008  # Slower target updates for stability
  alpha: 0.05  # Lower entropy for more focused policy
  automatic_entropy_tuning: true
  target_entropy: -2.0
  
  # Large buffer for better sample efficiency
  buffer_size: 5000000  # Very large buffer
  batch_size: 1024  # Larger batch size
  learning_starts: 10000  # More initial exploration
  
  # Optimized training frequency
  train_freq: 2  # Less frequent but more intensive training
  gradient_steps: 8  # Multiple gradient steps per update
  target_update_freq: 2  # Less frequent target updates
  
  policy_delay: 1
  target_policy_noise: 0.15
  target_noise_clip: 0.4

# Advanced exploration strategy
exploration:
  action_noise_type: "gaussian"  # Add exploration noise
  action_noise_std: 0.05  # Small noise for fine-tuning
  
  exploration_schedule:
    enabled: true
    initial_noise: 0.3
    final_noise: 0.05
    decay_steps: 1000000
